# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish" # UNCOMMENT THIS LINE
baseURL = "https://blog.hrod.dev/"
languageCode = "es"
defaultContentLanguage = "es"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

# googleAnalytics = "G-XXXXXXXXX"

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10

[params.tailwind]
  [params.tailwind.config.theme.extend.colors]
    nord-red = "#bf616a"
    nord-orange = "#d08770"
    nord-yellow = "#ebcb8b"
    nord-green = "#a3be8c"
    nord-purple = "#b48ead"
    nord-azure = "#88c0d0"
    nord-frost-1 = "#8fbcbb"
    nord-frost-2 = "#88c0d0"
    nord-frost-3 = "#81a1c1"
    nord-frost-4 = "#5e81ac"
